### PR TITLE
Changed the bg color, terminal font, and added a heading

### LINKED ISSUE #33: Changing the appearance of the Portfolio.
Pull Request Link --> https://github.com/thtauhid/terminal-portfolio/pull/32

Portfolio after updating :
port

Portfolio before updating :
port 0

Since the portfolio was looking quite unattractive from UI point of view, I have updated the UI of the portfolio to some extend.
My changes :
1. Changed the Bg color (Added a gradient).
2. Added a Heading.
3. Added a Subheading.
4. Added a Hint.
5. Styled using Tailwind CSS.

I hope this will get approved for Hacktoberfest 2023!

### PR DESCRIPTION
**Pull request by Ayansaxena24**
Since the portfolio was not looking attractive, I have added a background color along with a heading and two subheadings with hints and instructions. Hope you will like it. I have used Tailwind CSS for styling here.

Portfolio after changes : 
port

Portfolio before changes : 
port 0

### CODE REVIEW

**Comment by thtauhid** [comment]
Hi @Ayansaxena24 

Nice work. 

Here are a few things you need to take care of before I can merge this PR -
- Untrack `.history` folder - This folder is not necessary and you might have added this folder by mistake. Please remove the folder from git. 
- It's not a standard practice to push the `package.json` or `package-lock.json` file unless you add/remove new dependency or create/remove new scripts. So, for this PR it'd be better not to push the `package.json` or `package-lock.json` file. 
- I have added one comment related to styling in vercel preview. Check that one also.

Do let me know if you get stuck or need any help.

Looking forward to seeing you succeed in your open-source journey. 

Regards
THT

**Comment by Ayansaxena24** [comment]
Hey @thtauhid 
Please give me the access to the Vercel Dashboard. I have requested for the same on vercel.

Secondly, can you please guide me on how to undo pushing the 'package.json' file?

**Comment by thtauhid** [comment]
Hi @Ayansaxena24 

1. Please merge the `main` branch into your feature branch to solve any possible merge conflicts. 
2. Here's the comment that I left previously.
image
3. I'll write a separate comment on how you can remove the `package.json` and `package-lock.json` from this PR

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by thtauhid** [comment]
So the easiest way to fix the issues with `package.json` and `package-lock.json` will be to do the following- 
1. Go to `package.json` line 29
2. Replace the line with `"typescript": "^5.0.2",`
3. Go to `package-lock.json` line 27
4. Replace the line with `"typescript": "^5.0.2",`
5. Commit & Push

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by Ayansaxena24** [comment]
Hello @thtauhid 
I have removed the Hover Effect as required, but after resolving the merge conflicts Vercel deployment shows the status 'FAILED". Can you please throw some light on it? I have never used Vercel actually.

**Comment by thtauhid** [comment]
Give me some time. 
I'll check what's wrong.

**Comment by thtauhid** [comment]
@Ayansaxena24 somehow the .history folder got added again. 
Can you take care of that, please?

Once you take care of that, I'll check the deployment issue.

**Comment by Ayansaxena24** [comment]
I asked GPT about this and I followed the same steps.

gfg

Do i need to delete the history folder from my local project completely and then push?
Sorry for bothering you I am contributing in Open Source for the first time.

**Comment by thtauhid** [comment]
> Sorry for bothering you I am contributing in Open Source for the first time.
Not an issue. Happy to help. 

Run the following command- 
```
git rm --cached -r .history
```

Add `.history` in .gitignore

Then create a commit as usual. 

Let me know if you need more help.

**Comment by Ayansaxena24** [comment]
@thtauhid 
Can you check now please. Followed all the steps

**Comment by thtauhid** [comment]
@Ayansaxena24 there were some minor issues. 
Most probably it happened when you merged the main branch into your feature branch. 
It's solved now. 

Don't forget to pull the changes to your local machine before doing new commits. 

I'll review this PR in some time.

**Comment by thtauhid** [comment]
Hi @Ayansaxena24 
1. Can we convert this welcome message + hints + introductions into a welcome section? Just search `terminal welcome message` in google. 
2. Whenever a user runs the `clear` command the welcome section has to go away. You can introduce a new state for that I think.

**Comment by Ayansaxena24** [comment]
Hey @thtauhid 

> 2. Whenever a user runs the `clear` command the welcome section has to go away. You can introduce a new state for that I think.

I have completed this. Couldn't understand what to do in the first change requested by you. Hope it is covered in my deployment. Please review it.

**Comment by thtauhid** [comment]
@Ayansaxena24 nice work.
Here are a few things you need to address -
1. On the left side everything should be aligned 
image
2. When I cross the default screen height I lose the background. Consider adding a solid color as a background and removing the gradient background maybe? 
image

**Comment by Ayansaxena24** [comment]
hey @thtauhid 
I have modified the CSS as required. I have solved the issue of the height of the gradient too without removing the gradient. Please review it.

**Comment by thtauhid** [comment]
Can you check the mobile view also? 
It looks like this
image

**Comment by Ayansaxena24** [comment]
Hello @thtauhid 
In my phone this view is available. I am not able to understand what changes are need to be made. Can you please describe in more detail? 

Screenshot_2023-10-10-17-55-36-45_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Ayansaxena24** [comment]
Hello @thtauhid 
Can you please accept this for Hacktoberfest 2023?

**Pull request closed without merging**
