### PR TITLE
Updated Readme With Vercel Analytics #15

### PR DESCRIPTION
**Pull request by vr-varad21**

### CODE REVIEW

**Comment by thtauhid** [comment]
Can you make the title h3 instead of h2?

`##` -> `###`

**Comment by vr-varad21** [comment]
sure

**Comment by vr-varad21** [comment]
for every h2 or for vercel analytics part

**Comment by thtauhid** [comment]
Only this part only
`## Deploying to Vercel`

**Review by thtauhid — APPROVED** [review]

**Comment by vr-varad21** [comment]
done

**Comment by thtauhid** [comment]
@vr-varad21 thanks for creating the awesome guide. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Pull request merged**
