### PR TITLE
Deploy to netlify

### PR DESCRIPTION
**Pull request by infiniteltd**
Updated the README.md file to fix issue #62 "documentation on how to deploy to netlify".

### CODE REVIEW

**Comment by thtauhid** [comment]
1. Please remove or rephrase the line `Considering the fact that they are a large web hosting server as compared to vercel.` 
We don't want to mention which provider is larger. 
2. Consider removing the `bash` prefix 
image

Everything else looks good.

**Comment by infiniteltd** [comment]
Changes made. Please view and update.

**Review by thtauhid — CHANGES_REQUESTED** [review]
Can you uncomment this part? 

```
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200
```

**Comment by infiniteltd** [comment]
I can't seem to find this section in the project. Please can you point me to the right place where you saw it ?

**Comment by thtauhid** [comment]
Please check the attached image
image

**Comment by infiniteltd** [comment]
Hello can you check again?

**Comment by thtauhid** [comment]
Hi @infiniteltd 
Remove the `netlify.toml` file altogether.

**Pull request closed without merging**
