### PR TITLE
Feat/new themes

### PR DESCRIPTION
**Pull request by Vilayat-Ali**
1. Added 3 new themes - ubuntu, arch, matrix
2. added validation and execution function for theme related functionality.
3. Run *theme* to get list all commands associated to theme.
4. Run *theme list* to get list all available themes.
5. Run *theme set <theme_name>* to set theme to <theme_name>

Screenshot from 2023-10-05 03-42-43

Screenshot from 2023-10-05 03-42-33

Screenshot from 2023-10-05 03-42-07

Screenshot from 2023-10-05 03-41-47

### CODE REVIEW

**Comment by thtauhid** [comment]
Nice work. I really like the implementation. 
Can you take care of the following-
1. We are migrating all features of `Homepage` to `Profile` page as `Homepage` will be rebuilt. Please migrate this feature to the `Profile` page. 
2. Ideally, the full command should be stored in history. It's just storing the first word. 
image


I'm super excited for this feature.

**Comment by Vilayat-Ali** [comment]
Changes are on their way

**Comment by Vilayat-Ali** [comment]
Fix: : Migrated theme functionality to Profile.tsx and fixed incomplete command history entries.

- Migrated theme change functionality from Home.tsx to Profile.tsx
- `history` command shows complete theme command as passed by user

**Comment by Vilayat-Ali** [comment]
@thtauhid all changes have been made as per requested earlier. Can you quickly look into it and merge it?

**Comment by thtauhid** [comment]
@Vilayat-Ali checking this now.

**Review by thtauhid — APPROVED** [review]

**Comment by thtauhid** [comment]
@Vilayat-Ali nice work.

**Pull request merged**
