### PR TITLE
Added prettier configuration

### LINKED ISSUE #44: Add Prettier config file

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
closes #44

### CODE REVIEW

**Review by thtauhid — CHANGES_REQUESTED** [review]
Hi,
Please make the following changes- 
1. Add `package-lock.json` in prettier ignore file

Everything else looks good.

**Comment by DivyanshiNarang** [comment]
Hello, I have made the changes. Please review it.

**Review by thtauhid — APPROVED** [review]

**Comment by thtauhid** [comment]
Closes #44 #45 #46

**Comment by thtauhid** [comment]
@DivyanshiNarang thank you for the valuable contribution.

**Pull request merged**
