### PR TITLE
fixes: Scroll down automatically

### PR DESCRIPTION
**Pull request by relativvv**

### CODE REVIEW

**Review by thtauhid — CHANGES_REQUESTED** [review]
Hi,

It doesn't work when I am testing. 
Can you take a look?
If it's working on your device, please provide a short video/loom.

**Comment by relativvv** [comment]
sorry, I found the issue, I also attach a video for the working example.

https://github.com/thtauhid/terminal-portfolio/assets/52501124/ac5638c2-b9f5-4198-adef-fbfffe5e55a0

**Review by thtauhid — APPROVED** [review]
LGTM

**Comment by thtauhid** [comment]
Thanks @relativvv for the contribution.

**Pull request merged**
