### PR TITLE
updating so that only first word is taken as command

### PR DESCRIPTION
**Pull request by Paulie-Aditya**
Example writing $contact works but writing $contact 999 would not work since the entire input is being considered.

If we consider the command to be only the first word by using command = command.split()[0] and then running trim and tolowercase, we solve this problem

### CODE REVIEW

**Comment by Paulie-Aditya** [comment]
ok this recent one works
basically only one line of code, but it helps out in handling a few more cases

pls do consider this pr for hacktober

**Comment by thtauhid** [comment]
Hi @Paulie-Aditya 
Thanks for your interest. 

If we were to implement this we might not get the benefit from #3.

When #3 is implemented the command will look something like this
```
setname Jake
```

What are your thoughts? 


Regards
THT

**Comment by Paulie-Aditya** [comment]
we can just keep those as edge cases, say the command is setname, then we will also consider the first argument
basically a simple if else can be put in case to resolve that, not a big issue

**Comment by thtauhid** [comment]
Makes sense. 

Let's do one thing. 
I'll first merge #3 and then merge this one to avoid any code conflict. 
Does that work for you? 

This PR will be considered under hacktoberfest.

Thanks

**Comment by Paulie-Aditya** [comment]
yep, works for me 👍

**Comment by Paulie-Aditya** [comment]
just do let me know what all commands have to take in additional input (after finishing up #3), I'll fix it accordingly

**Comment by thtauhid** [comment]
Cool. I'll update you when #3 is merged.

**Comment by thtauhid** [comment]
#3 is merged. You can work on this now @Paulie-Aditya

**Comment by Paulie-Aditya** [comment]
@thtauhid done, Please do check the same and merge it upon success.

**Comment by thtauhid** [comment]
Hi @Paulie-Aditya 
If I enter `setname tauhid`, the space is getting removed between `setname` and `tauhid` and it's showing `command not found`. 
Can you check this once? 

image

**Comment by thtauhid** [comment]
@Paulie-Aditya you need to merge the main branch to your feature branch.

**Comment by Paulie-Aditya** [comment]
gimme some time, I'll mention you once this is fixed

**Comment by Paulie-Aditya** [comment]
nvm my code was fine, only had problems in taking previous merged stuff into account

**Comment by Paulie-Aditya** [comment]
cool @thtauhid , works now.
Please perform the necessary checks and approve if found satisfactory.

**Comment by thtauhid** [comment]
Nice work @Paulie-Aditya 

Looking forward to seeing more contributions from you in open source. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Review by thtauhid — APPROVED** [review]

**Pull request merged**
