### PR TITLE
build: introduce react-icons

### LINKED ISSUE #9: Icon support

### PR DESCRIPTION
**Pull request by sdanialraza**
This introduces react icons package and resolves #9.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
adding react-icons library to the package.json does not create any effect as it is not used anywhere in the project.

**Comment by sdanialraza** [comment]
I wasn't sure if the icons can already be used somewhere, can they be?

**Comment by Kritika30032002** [comment]
If it was used, then the library had been included. When we use any library then only we include it otherwise it affects performance of website.

**Comment by sdanialraza** [comment]
There was an issue open for this, so I would assume the icons would be used very soon.

**Comment by Kritika30032002** [comment]
Okay

**Pull request closed without merging**
