### PR TITLE
added history navigation

### PR DESCRIPTION
**Pull request by deafwired**
i also formatted with prettier

### CODE REVIEW

**Comment by thtauhid** [comment]
Nice work. 

It'd be great if you can take care of two more things-
1. When we run the `clear` command, if we press the arrow up key we are supposed to see the previous command(s). But nothing is shown. 
2. When we navigate through the history if we come to the last item and press the arrow down key it should clear the prompt area, but it doesn't. It shows the last command. 

Let me know if this makes sense, otherwise, I'll create a video. 


Thanks for the awesome work.

**Comment by deafwired** [comment]
from what i can see, when you clear, it sets the history to an empty array, should this not happen?
```ts
else if (command === "clear") {
        setHistory([]);
)
```

**Comment by thtauhid** [comment]
I think we need to rewrite the code such that- 
When we run `clear` it clears the UI. Maybe we can keep two states. One that handles the elements that we'll display. Another state can just preserve the command history. We can use the later to navigate. These are just my thoughts. Might be there is a better approach? 

If you want to take up the rewrite task that'd be awesome. 
If not, it's perfectly fine as you have done the main implementation. 

Do let me know your thoughts.

Thanks

**Comment by deafwired** [comment]
I added the clearing when you press downarrow, but tbh i don't know typescript that well and have been relying on javascript knowlege.

**Comment by thtauhid** [comment]
@deafwired cool. 
You are a brilliant guy! 

Thanks very much for the contribution.

**Review by thtauhid — APPROVED** [review]
LGTM

**Pull request merged**
