### PR TITLE
style: visit projects added

### PR DESCRIPTION
**Pull request by Y1a2s3h4**
- added url property in data.
- added a tag for project visiting.

### CODE REVIEW

**Comment by thtauhid** [comment]
This is the build log: 
[00:05:37.594] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[00:05:37.712] Cloning github.com/thtauhid/terminal-portfolio (Branch: visitPortfolio, Commit: 1ca2b96)
[00:05:37.969] Cloning completed: 255.962ms
[00:05:39.442] Restored build cache
[00:05:39.514] Running "vercel build"
[00:05:39.959] Vercel CLI 32.3.1
[00:05:40.560] Installing dependencies...
[00:05:41.539] 
[00:05:41.539] removed 32 packages in 658ms
[00:05:41.540] 
[00:05:41.540] 51 packages are looking for funding
[00:05:41.540]   run `npm fund` for details
[00:05:41.555] Detected `package-lock.json` generated by npm 7+
[00:05:41.555] Running "npm run build"
[00:05:41.976] 
[00:05:41.976] > terminal-portfolio@0.0.0 build
[00:05:41.976] > tsc && vite build
[00:05:41.976] 
[00:05:43.255] src/App.tsx(26,74): error TS2339: Property 'url' does not exist on type '{ label: string; value: string; } | { label: string; value: string; url: string; }'.
[00:05:43.255]   Property 'url' does not exist on type '{ label: string; value: string; }'.
[00:05:43.278] Error: Command "npm run build" exited with 2

This is where the error occurred
image

Do let me know if you need help in navigating the error.

**Comment by thtauhid** [comment]
Looks great. 
The project has conflict with the base branch. 

Please merge the main branch into your feature branch and check for conflicts.

**Comment by Y1a2s3h4** [comment]
image
How come this passed the TS warning build test I merged but how this code was pushed previously?

if now i remove this one I'll get merge issue again.

and obviously this warning is correct, we can change this 
image

If else to single if statement.

image


What should i do now ?

**Comment by thtauhid** [comment]
You can ignore that for now.

**Comment by Y1a2s3h4** [comment]
I just copied same to same code and pasted it.
image

just spaces issue

**Comment by thtauhid** [comment]
I'll check.

**Comment by Y1a2s3h4** [comment]
ok great.
I'm open for any kind of contributions 😄

**Comment by thtauhid** [comment]
Hi @Y1a2s3h4 
I would like to know if you deleted these lines by mistake in `App.tsx`?

```js
import { Queue } from "queue-typescript";

const historyCommand = new Queue<string>();
let count = 1;
let historyPos = 1;
```

**Comment by Y1a2s3h4** [comment]
Yes Might Be Deleted By Mistakenly. But I did'nt saw this code before when I pull the fork

**Comment by Y1a2s3h4** [comment]
What happened? No response?

**Comment by thtauhid** [comment]
Hi @Y1a2s3h4 
All maintainers work voluntarily and they have their day jobs/ studies to take care of. 
We try to respond as quickly as possible but that's always not possible. 

Please merge the main branch to your feature branch correctly so we can get it merged. 
When you merge the main branch all the updated code will get pulled into your feature branch. 

Sometimes when merging the main branch into the feature branch it might happen that you delete necessary code accidentally. 
This is the same case for this PR. 

You either need to merge the main branch correctly or you can also rebase (not recommended if you are a beginner)
You can also consider creating a new PR.

Thank you

**Comment by thtauhid** [comment]
@Y1a2s3h4 do leave a comment when you think the PR is ready for review.

**Comment by thtauhid** [comment]
Hi @Y1a2s3h4 
This pull request is yet to be merged. 
Will notify you when the PR gets merged.

**Comment by thtauhid** [comment]
PR looks good. 
New issue will be created to migrate this feature into `Profile` page.

**Pull request merged**
